
FROM ghcr.io/opennmt/ctranslate2:4.3.1-ubuntu20.04-cuda12.2

# Set environment variables
ENV TZ=America/Los_Angeles
ENV DEBIAN_FRONTEND=noninteractive


# Update system
RUN apt-get update -y && apt-get upgrade -y

# Install required dependencies
RUN apt-get install -y build-essential libssl-dev zlib1g-dev libbz2-dev \
    libreadline-dev libsqlite3-dev wget curl llvm libncurses5-dev libncursesw5-dev \
    xz-utils tk-dev libffi-dev liblzma-dev python-openssl git

# Download Python 3.12 source code
RUN wget https://www.python.org/ftp/python/3.12.0/Python-3.12.0.tgz

# Extract the archive
RUN tar -xf Python-3.12.0.tgz

# Configure and build Python 3.12
WORKDIR Python-3.12.0
RUN ./configure --enable-optimizations
# Determine how many cpu cores to use.
RUN make -j 8

# Install Python 3.12
RUN make altinstall

# Verify installation
RUN python3.12 --version

# Clean up
WORKDIR /
RUN rm -rf Python-3.12.0 Python-3.12.0.tgz

# Default command to run when starting the container
ENTRYPOINT ["bash"]
