# Start with the latest CTranslate2 image from https://github.com/OpenNMT/CTranslate2/tree/master/docker
FROM ghcr.io/opennmt/ctranslate2:4.3.1-ubuntu20.04-cuda12.2

# Add Python 3.12 to the image

# Set environment variables
ENV TZ=America/Los_Angeles
ENV DEBIAN_FRONTEND=noninteractive


# Update system and install required dependencies
RUN apt-get update -y && apt-get upgrade -y && \
    apt-get install -y build-essential libssl-dev zlib1g-dev libbz2-dev \
    libreadline-dev libsqlite3-dev wget curl llvm libncurses5-dev libncursesw5-dev \
    xz-utils tk-dev libffi-dev liblzma-dev python-openssl git && \
    rm -rf /var/lib/apt/lists/*

# Build Python 3.12
RUN wget https://www.python.org/ftp/python/3.12.0/Python-3.12.0.tgz && \
    tar -xf Python-3.12.0.tgz && \
    cd Python-3.12.0 && \
    ./configure --enable-optimizations && \
    make -j 8 && \
    make altinstall && \
    python3.12 --version && \
    cd .. && \
    rm -rf Python-3.12.0 Python-3.12.0.tgz

# Default command to run when starting the container
ENTRYPOINT ["bash"]
